# S2 - Introduction to Pandas and Data Frames
----

In the first notebook, we explored ways in which basic python could be used. However, often that is very difficult and un-intuitive. 

What we really would like is to use dataframes (excel type data structures) where we have our data organized in a clean table. For that we will use pandas. 

Pandas stands for "Python Data Analysis Library" (https://pandas.pydata.org/) 

You can access the API documentation here.(https://pandas.pydata.org/docs/reference/index.html)

Below, I will walk through many key functions.

In [ ]:
# Loading the Pandas Packages # 

import pandas as pd

To work with Pandas, we need to use a dataset. That file can be remote, but we will use a local file (saved on our google drive) 

## S2.1 - Let's load the dataset located on Google Drive

In [ ]:
# Then we load our drive - You might have to follow along on some intermediate steps #

from google.colab import drive    

drive.mount('/content/drive')

Mounted at /content/drive

You can run the command : *ls*    to see the files availible in a directory. You can also explore this on the file explorer on the left.

In [ ]:
ls

drive/  sample_data/

In [ ]:
import os 

# We change directory to the directory below - This will differ on your system #
os.chdir("./drive/MyDrive/Teaching/DSO 574/Notebooks for Python Workshops/Data Files")

In [ ]:
ls

LA2020listings.csv  LA2020neighbourhoods.csv  LA2020reviews.csv

In [ ]:
# Lets load the AirBnB Listing Data # 

data = pd.read_csv("./LA2020listings.csv")

## S2.2 - Exploring the Data
--- 
Now we have a AirBnB data saved in an object called "*data*", we can explore this below. We can begin exploring the data.


### S2.2.A - Seeing What the Data Looks Like

In [ ]:
# See the First Five Lines of the Dataset # 

data.head(5)

     id  ... availability_365
0   109  ...              216
1  2708  ...              360
2  2732  ...              337
3  2864  ...                0
4  5728  ...              337

[5 rows x 16 columns]

In [ ]:
# See the Last Two Lines of the Dataset # 

data.tail(2)

             id  ... availability_365
31469  46201177  ...              324
31470  46202156  ...              335

[2 rows x 16 columns]


### S2.2.B - Seeing the Variables in the Data

In [ ]:
# Seeing the Columns (Variable Names) that we have in the data #

data.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [ ]:
# Describe the data we have - Calculates Count, Mean, Standard Deviation, Min, Max (Quartiles)  - Only for Numeric Variables (Int & Float) #

data.describe()

                 id  ...  availability_365
count  3.147100e+04  ...      31471.000000
mean   2.716854e+07  ...        174.973531
std    1.399423e+07  ...        142.622594
min    1.090000e+02  ...          0.000000
25%    1.588855e+07  ...         28.000000
50%    2.852832e+07  ...        162.000000
75%    4.023249e+07  ...        336.000000
max    4.620216e+07  ...        365.000000

[8 rows x 10 columns]

In [ ]:
# You can also calculate these metrics for individual variables #

data['price'].mean()

220.564265514283

In [ ]:
# Lets see the number of rows and columns in the data (N Rows, N Columns) # 

data.shape

(31471, 16)

In [ ]:
# We can also summarize string data (groups) as well # 

data['room_type'].describe()

count               31471
unique                  4
top       Entire home/apt
freq                20292
Name: room_type, dtype: object

In [ ]:
# To see a breakdown of the unique values # 

data['room_type'].value_counts()

Entire home/apt    20292
Private room        9981
Shared room         1042
Hotel room           156
Name: room_type, dtype: int64

In [ ]:
# We can also add variants to change the output. By adding normalize we can see the proportion (share) rather than the total number #

data['room_type'].value_counts(normalize = True)

Entire home/apt    0.644784
Private room       0.317149
Shared room        0.033110
Hotel room         0.004957
Name: room_type, dtype: float64

## S2.3 - Selecting a "Piece" of the Data

---

Sometimes we only want a portion of the data. 

*   We only want certain columns, either to make the data more manegable or to save space. 
*   We only want certain rows becauswe we are interested in a certain subset of data

Below, I present several techniques you can use to selecting only certian rows.

In [ ]:
# Select only certain columns #

OnlyPrice_and_Location = data[['id', 'price', 'neighbourhood']]

OnlyPrice_and_Location.head()

     id  price neighbourhood
0   109    115   Culver City
1  2708     71     Hollywood
2  2732    155  Santa Monica
3  2864     50    Bellflower
4  5728     60       Del Rey

In [ ]:
# To select rows, we have to specify conditions. Let's look only at data in Santa Monica #

SantaMonicaData = data.loc[data['neighbourhood'] == 'Santa Monica']

# See Output # 
SantaMonicaData.head(2)

       id  ... availability_365
2    2732  ...              337
41  30725  ...              365

[2 rows x 16 columns]

In [ ]:
# We can also make more complex queries, by combining several conditions. Lets look only at "Entire Homes" in Stanta Monica # 

SantaMonicaData = data.loc[data['neighbourhood'] == 'Santa Monica']
EntireHomesInSantaMonica = SantaMonicaData.loc[SantaMonicaData['room_type'] == "Entire home/apt" ]

# Or you can do it in one line #

EntireHomesInSantaMonica = data.loc[ (data['neighbourhood'] == "Santa Monica") & (data['room_type'] == "Entire home/apt")]

# See Output # 
EntireHomesInSantaMonica.head(2)

       id  ... availability_365
46  35922  ...              365
79  67672  ...              266

[2 rows x 16 columns]

In [ ]:
# You can also use this to find "Or" conditions, such as Santa Monica or Culver City #

SantaMonicaOrCulverCity = data.loc[ (data['neighbourhood'] == "Santa Monica") | (data['neighbourhood'] == "Culver City")]

# See Output # 
SantaMonicaOrCulverCity.head(2)

     id  ... availability_365
0   109  ...              216
2  2732  ...              337

[2 rows x 16 columns]

## S2.3 - Adding New Variables or Combining Data
--- 

You may want to add new variables to a python data frame. For example, you might want to calculcate how far a rental is above or below the average price.

In [ ]:
# We can calculate the average price using the fucntions from above # 

data['price'].mean()

220.564265514283

In [ ]:
# We can add this to a new column simply as ..

data['average_price'] = data['price'].mean()

In [ ]:
# We can then calculcate the difference as ...

data['price_gap'] = data['price'] - data['average_price']

# or all in one line with ... 

data['price_gap'] = data['price'].mean() - data['average_price']

Sometimes, we may want to compare the average within groups. For example, compare the apartments in Santa Monica to the average price in Santa Monica. 

Lets repeat this for Santa Monica and Culver City.

In [ ]:
# Select Only Data for Santa Monica #

SM = data.loc[ (data['neighbourhood'] == "Santa Monica") & (data['room_type'] == "Entire home/apt")]

# Select Only Data for Culver City # 

Culver = data.loc[ (data['neighbourhood'] == "Culver City") & (data['room_type'] == "Entire home/apt")]

# Calculate Averages for each group # 

SM['price_gap'] = SM['price'].mean() - SM['average_price']

Culver['price_gap'] = Culver['price'].mean() - Culver['average_price']

# We get some warnings, but this is not a big deal -- Python is warning us that this is not the best form, but its clear and intuitive #

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [ ]:
# Lets just check we have the data # 

SM.shape, Culver.shape

((873, 18), (204, 18))

In [ ]:
# Combining the Data - We use the Concatenate function. It adds the two datasets, end to end # 

CombinedData = pd.concat([SM, Culver])

In [ ]:
# Just to Confirm, Lets see the first few rows #

CombinedData.head(2)

       id                                 name  ...  average_price  price_gap
46  35922  Luxury Beachfront Santa Monica Home  ...     220.564266 -12.235514
79  67672                furnished one bedroom  ...     220.564266 -12.235514

[2 rows x 18 columns]

In [ ]:
# Lets also check the last few #

CombinedData.tail(2)

             id  ...  price_gap
31169  46056466  ... -45.559364
31314  46114643  ... -45.559364

[2 rows x 18 columns]

## S2.3 - Merging Different Data Frames
-----
Where Python, SQL, R and other languages really start to show their use, and differentiate themselves from tools such as Excel is when it comes to merging and combining datasets.  

It is often most efficient to store datasets in smaller individual tables and then combine them as needed. (Efficient meaning it takes less space on your computer to store, and less time to load and perform operations)

In [ ]:
# Load Dataset #1: Listing Data # 

listings = pd.read_csv("./LA2020listings.csv")

In [ ]:
# Load Dataset #2: Listing Data # 

reviews = pd.read_csv("./LA2020reviews.csv")

In [ ]:
# Let's look at both datasets to get a sense of the data # 

listings.head(5)

     id  ... availability_365
0   109  ...              216
1  2708  ...              360
2  2732  ...              337
3  2864  ...                0
4  5728  ...              337

[5 rows x 16 columns]

In [ ]:
reviews.head(5)

   listing_id        date
0         109  2011-08-15
1         109  2016-05-15
2        2708  2014-06-09
3        2708  2014-06-23
4        2708  2015-07-25

In the *reviews* data we have a single column listing the date of each review and an identifier (listing_id). This identifier is useful becuase it also applies to the listing data table. 

Using *listing_id* we can combine the data from these different tables. 

Suppose that to the reviews data, we would like to add a column that indicates the neighbourhood of the listing and the hostname.

In [ ]:
# Step #1. Let's select only the relevant variables for the listing data # 

ColumnsFromListing = listings[['id', 'neighbourhood', 'host_name']]

ColumnsFromListing.head()

     id neighbourhood       host_name
0   109   Culver City           Paolo
1  2708     Hollywood           Chas.
2  2732  Santa Monica  Yoga Priestess
3  2864    Bellflower       Bernadine
4  5728       Del Rey           Sanni

In [ ]:
# Step #2. Merge or Join the Two datasets (Basically add the columns from one to the other)

reviews.merge(ColumnsFromListing, left_on = 'listing_id', right_on = 'id', how = 'inner')

         listing_id        date        id   neighbourhood            host_name
0               109  2011-08-15       109     Culver City                Paolo
1               109  2016-05-15       109     Culver City                Paolo
2              2708  2014-06-09      2708       Hollywood                Chas.
3              2708  2014-06-23      2708       Hollywood                Chas.
4              2708  2015-07-25      2708       Hollywood                Chas.
...             ...         ...       ...             ...                  ...
1088923    46077780  2020-10-29  46077780      Long Beach                 Anna
1088924    46118587  2020-10-30  46118587          Malibu  The Nightfall Group
1088925    46154941  2020-11-02  46154941     Canoga Park                Shawn
1088926    46156346  2020-11-01  46156346  Valley Village       Hotel Mariposa
1088927    46156346  2020-11-02  46156346  Valley Village       Hotel Mariposa

[1088928 rows x 5 columns]

Above, we can see that we now have added to the reviews data, all of the data from the listing data table. 

Let's decompose this command. 

There are two datasets: 
- The Left: Reviews. This is the dataset that is the base that we are attaching the other one to.
- The Right: ColumnsFromListing. This is the dataset we are attaching to the base dataset. 

We specify the command as : Left_Dataset.merge(Right_Dataset)

We also have to specify what to merge on. This means what are the variables that are the same across both datasets that we can use to combine. 

- left_on: indicates the name of the variable in the Left dataset. 
- right_on: indicates the name of the variable in the Right dataset. 

If the variable has the same name in both, you can only specify "on" instead of left_on, right_on. 

There are also different types of joins. 

- Inner: Keep only the values where both datasets match up (left_on and right_on is the same in both)
- Left: Keep all of the observations in the Left, but only those in the Right dataset that match up. 
- Right: Keep all of the observations in the Right, but only those in the Left dataset that match up. 
- Outer: Keep all of the observations including those that existing in both datasets, but also those that do not. 

This is indicated in the **how = 'inner'** command. If you do specify anything  then you get an inner join by default. 

You can find more details explaining these commands here. 

https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#:~:text=merge%20is%20a%20function%20in%20the%20pandas%20namespace,,the%20index-on-index%20(by%20default)%20and%20column%20(s)-on-index%20join.

In [ ]:
# We would normally save this with annother name in order to be able to access this later #

merged_data = reviews.merge(ColumnsFromListing, left_on = 'listing_id', right_on = 'id', how = 'inner')

## Where to go next? 

These are the most basic data skills you will need from this class. Using the commands above, I believe that you should be able to do most of what you want / need for the assignments in this class. 

Depending on how you feel about the assignment, I would suggest taking a few different steps. 

- If you felt like this was easy and obvious. You have experience with python. Move along to later notebooks. 
- If you would like more practice with this, then I would suggest using the comamands above to explore the AirBnB dataset and look for interesting new patterns. 

If you need to understand more about some of these commands, do not hesitate to access the documentation (https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) and explore some additional functionality.